### ISSUE TITLE
Question about the Raspberry pi example

### ISSUE THREAD

**Issue by gilles537** [kubeedge/examples#22]
I have followed the guide and now i have the deployments running but the pod keeps crashing. When i check the actual container the logs says: 

I0613 14:02:34.782924       1 light_mapper.go:168] Changing the state of the device to online
I0613 14:02:34.784542       1 light_mapper.go:242] Watching on the device twin values for device: led-light-instance-01
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66e450]

goroutine 1 [running]:
main.equateTwinValue(0x0, 0x0, 0x0, 0x400007d2f0)
	/var/opt/godir/src/github.com/kubeedge/examples/led-raspberrypi/light_mapper.go:248 +0x198
main.main()
	/var/opt/godir/src/github.com/kubeedge/examples/led-raspberrypi/light_mapper.go:280 +0x16c

**Comment by sujithsimon22** [comment]
@gilles537 This problem is caused since the desired value has not been set yet. We have to set the desired value for "power-status" in the device instance
 I'll raise a PR for the error handling here & edit the device instance placed at "led-raspberrypi/sample-crds/led-light-device-instance.yaml" to include the desired value
